development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:703e721a6754277b4a98428de661e415@scat.redistogo.com:9933/
  channel_prefix: chatme-app_production
